/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedConnectAccountsRouteImport } from './routes/_authenticated/connect-accounts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPaymentLinksRouteImport } from './routes/_authenticated/payment-links'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as ApiPublicPlanWebhookRouteImport } from './routes/api/public/plan-webhook'
import { Route as ApiPublicPaymentsPollRouteImport } from './routes/api/public/payments/poll'
import { Route as ApiPublicV1CreateOrderRouteImport } from './routes/api/public/v1/create-order'
import { Route as ApiPublicV1OrderStatusRouteImport } from './routes/api/public/v1/order-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectAccountsRoute =
  AuthenticatedConnectAccountsRouteImport.update({
    id: '/connect-accounts',
    path: '/connect-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentLinksRoute =
  AuthenticatedPaymentLinksRouteImport.update({
    id: '/payment-links',
    path: '/payment-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlanWebhookRoute = ApiPublicPlanWebhookRouteImport.update({
  id: '/api/public/plan-webhook',
  path: '/api/public/plan-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsPollRoute = ApiPublicPaymentsPollRouteImport.update({
  id: '/api/public/payments/poll',
  path: '/api/public/payments/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CreateOrderRoute = ApiPublicV1CreateOrderRouteImport.update({
  id: '/api/public/v1/create-order',
  path: '/api/public/v1/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrderStatusRoute = ApiPublicV1OrderStatusRouteImport.update({
  id: '/api/public/v1/order-status',
  path: '/api/public/v1/order-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/connect-accounts': typeof AuthenticatedConnectAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment-links': typeof AuthenticatedPaymentLinksRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/order-status': typeof ApiPublicV1OrderStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/connect-accounts': typeof AuthenticatedConnectAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment-links': typeof AuthenticatedPaymentLinksRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/support': typeof AuthenticatedSupportRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/order-status': typeof ApiPublicV1OrderStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/connect-accounts': typeof AuthenticatedConnectAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payment-links': typeof AuthenticatedPaymentLinksRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/pay/$slug': typeof PaySlugRoute
  '/api/public/plan-webhook': typeof ApiPublicPlanWebhookRoute
  '/api/public/payments/poll': typeof ApiPublicPaymentsPollRoute
  '/api/public/v1/create-order': typeof ApiPublicV1CreateOrderRoute
  '/api/public/v1/order-status': typeof ApiPublicV1OrderStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/api-keys'
    | '/connect-accounts'
    | '/dashboard'
    | '/payment-links'
    | '/plan'
    | '/support'
    | '/transactions'
    | '/pay/$slug'
    | '/api/public/plan-webhook'
    | '/api/public/payments/poll'
    | '/api/public/v1/create-order'
    | '/api/public/v1/order-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/api-keys'
    | '/connect-accounts'
    | '/dashboard'
    | '/payment-links'
    | '/plan'
    | '/support'
    | '/transactions'
    | '/pay/$slug'
    | '/api/public/plan-webhook'
    | '/api/public/payments/poll'
    | '/api/public/v1/create-order'
    | '/api/public/v1/order-status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/_authenticated/api-keys'
    | '/_authenticated/connect-accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/payment-links'
    | '/_authenticated/plan'
    | '/_authenticated/support'
    | '/_authenticated/transactions'
    | '/pay/$slug'
    | '/api/public/plan-webhook'
    | '/api/public/payments/poll'
    | '/api/public/v1/create-order'
    | '/api/public/v1/order-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PaySlugRoute: typeof PaySlugRoute
  ApiPublicPlanWebhookRoute: typeof ApiPublicPlanWebhookRoute
  ApiPublicPaymentsPollRoute: typeof ApiPublicPaymentsPollRoute
  ApiPublicV1CreateOrderRoute: typeof ApiPublicV1CreateOrderRoute
  ApiPublicV1OrderStatusRoute: typeof ApiPublicV1OrderStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect-accounts': {
      id: '/_authenticated/connect-accounts'
      path: '/connect-accounts'
      fullPath: '/connect-accounts'
      preLoaderRoute: typeof AuthenticatedConnectAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-links': {
      id: '/_authenticated/payment-links'
      path: '/payment-links'
      fullPath: '/payment-links'
      preLoaderRoute: typeof AuthenticatedPaymentLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plan-webhook': {
      id: '/api/public/plan-webhook'
      path: '/api/public/plan-webhook'
      fullPath: '/api/public/plan-webhook'
      preLoaderRoute: typeof ApiPublicPlanWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/poll': {
      id: '/api/public/payments/poll'
      path: '/api/public/payments/poll'
      fullPath: '/api/public/payments/poll'
      preLoaderRoute: typeof ApiPublicPaymentsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/create-order': {
      id: '/api/public/v1/create-order'
      path: '/api/public/v1/create-order'
      fullPath: '/api/public/v1/create-order'
      preLoaderRoute: typeof ApiPublicV1CreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/order-status': {
      id: '/api/public/v1/order-status'
      path: '/api/public/v1/order-status'
      fullPath: '/api/public/v1/order-status'
      preLoaderRoute: typeof ApiPublicV1OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedConnectAccountsRoute: typeof AuthenticatedConnectAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentLinksRoute: typeof AuthenticatedPaymentLinksRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedConnectAccountsRoute: AuthenticatedConnectAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentLinksRoute: AuthenticatedPaymentLinksRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PaySlugRoute: PaySlugRoute,
  ApiPublicPlanWebhookRoute: ApiPublicPlanWebhookRoute,
  ApiPublicPaymentsPollRoute: ApiPublicPaymentsPollRoute,
  ApiPublicV1CreateOrderRoute: ApiPublicV1CreateOrderRoute,
  ApiPublicV1OrderStatusRoute: ApiPublicV1OrderStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
